config/routes.rb
Rails.application.routes.draw do
  resource :session, only: [:new, :create, :destroy]
  resources :regions, only: [:create, :show, :index]
  resource :questionnaire, only: [:show]
  resources :responses, only: [:new, :create]
  resources :conversations, only: [:index]
  resources :users, only: [:new, :create, :show, :edit, :update] do
    resources :messages, only: [:show, :create]
    resource :conversation, only: [:show]
  end

  root "regions#index"
end

app/models/message.rb
class Message < ActiveRecord::Base
  belongs_to :sender, class_name: "User"
  belongs_to :receiver, class_name: "User"

  validates :body, presence: true

  def self.between(user1, user2)
    where("(sender_id = :user1 AND receiver_id = :user2) OR
          (sender_id = :user2 AND receiver_id = :user1)",
          user1: user1.id, user2: user2.id).order(:created_at)
  end

  def self.to_or_from(user)
    where("sender_id = :id OR receiver_id = :id", id: user.id)
  end
end

app/models/question.rb
class Question < ActiveRecord::Base
  has_many :responses

  def self.next_for(user)
    all_unanswered = all.pluck(:id) - user.responses.pluck(:question_id)
    first_unanswered = all_unanswered.first
    first_unanswered && find(first_unanswered)
  end

  def response_for(user)
    responses.find_by(user_id: user.id)
  end
end

app/models/region.rb
class Region < ActiveRecord::Base
  validates :name, presence: true

  has_many :users
end

app/models/response.rb
class Response < ActiveRecord::Base
  belongs_to :question
  belongs_to :user

  validates :positive, inclusion: { :in => [true, false] }
end

app/models/user.rb
class User < ActiveRecord::Base
  validates :email, presence: true, uniqueness: true
  validates :password_digest, presence: true

  belongs_to :region
  has_many :responses
  has_many :messages, foreign_key: :receiver_id

  def self.communicated_with(user)
    messages = Message.to_or_from(user)
    receivers = messages.map(&:receiver_id)
    senders = messages.map(&:sender_id)
    to_and_from = (receivers + senders).uniq
    to_and_from.delete user.id
    where id: to_and_from
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include Monban::ControllerHelpers
  before_action :require_login
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/conversations_controller.rb
class ConversationsController < ApplicationController
  def index
    @users = User.communicated_with(current_user)
  end

  def show
    @other_user = User.find(params[:user_id])
    @messages = Message.between(current_user, @other_user)
    @message = current_user.messages.new
  end
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  def create
    @other_user = User.find(params[:user_id])
    @message = current_user.messages.new(message_params)
    if @message.save
      redirect_to user_conversation_path(@other_user)
    else
      flash[:error] = "Please write something"
      redirect_to user_conversation_path(@other_user)
    end
  end

  private

  def message_params
    params.require(:message).permit(:receiver_id, :body).
      merge(sender_id: current_user.id)
  end
end

app/controllers/questionnaires_controller.rb
class QuestionnairesController < ApplicationController
  def show
    @question = Question.next_for(current_user)
    @questions = Question.all
  end
end

app/controllers/regions_controller.rb
class RegionsController < ApplicationController
  def index
    @regions = Region.all
    @region = Region.new
  end

  def create
    @region = Region.new(region_params)
    if @region.save
      redirect_to root_path
    else
      @regions = Region.all
      render :index
    end
  end

  def show
    @region = Region.find(params[:id])
    @users = @region.users
  end

  private

  def region_params
    params.require(:region).permit(:name)
  end
end

app/controllers/responses_controller.rb
class ResponsesController < ApplicationController
  def new
    @question = Question.find(params[:question_id])
  end

  def create
    @response = current_user.responses.new(response_params)

    if !@response.save
      flash[:error] = "Please choose an answer"
    end

    redirect_to questionnaire_path
  end

  private

  def response_params
    params.require(:response).permit(:question_id, :positive)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  skip_before_action :require_login, only: [:new, :create]

  def new
  end

  def create
    user = authenticate_session(session_params)

    if sign_in(user)
      redirect_to root_path
    else
      render :new
    end
  end

  def destroy
    sign_out
    redirect_to root_path
  end

  private

  def session_params
    params.require(:session).permit(:email, :password)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  skip_before_action :require_login, only: [:new, :create, :show]

  def new
    @user = User.new
  end

  def create
    @user = sign_up(user_params)

    if @user.valid?
      sign_in(@user)
      redirect_to root_path
    else
      render :new
    end
  end

  def show
    @user = User.find(params[:id])
    @personal_statement = @user.personal_statement
    @image = @user.image
    @responses = @user.responses
  end

  def edit
    @user =  User.find(params[:id])
  end

  def update
    user = User.find(params[:id])
    user.update(user_params)
    if params[:back]
      redirect_to :back
    else
      redirect_to user
    end
  end

  private

  def user_params
    params.require(:user).
      permit(:email, :password, :personal_statement, :image, :region_id)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/application/_error_messages.html.erb
<% if target.errors.any? %>
  <h2><%= pluralize target.errors.count, "error" %> prevented the form from saving</h2>
<ul>
  <% target.errors.each do |error| %>
    <li><%= error %></li>
  <% end %>
</ul>
<% end %>

app/views/conversations/index.html.erb
<div id="container">
  <div id="conversation">
    <h2>Your conversations</h2>
    <ul>
      <% @users.each do |user| %>
        <li>
          <%= link_to user.email, user_conversation_path(user) %>
        </li>
    <% end %>
    </div>
    <div id="talkingdead">
      <img src="<%= asset_path "shawn_zombie.jpg" %>" alt="Talking Dead">
    </div>
  </ul>
</div>

app/views/conversations/show.html.erb
<div id="container">
  <div id="conversation">
    <h2>Conversation with <%= @other_user.email %></h2>
    </br>
    <ul>
      <% @messages.each do |message| %>
        <% if message.sender != current_user %>
          <li><b><%= message.sender.email %></b> - <%= message.body %></li>
        <% else %>
          <li><b>Me</b> - <%= message.body %></li>
        <% end %>
      <% end %>
    </ul>
    </br>
    <%= render "messages/form" %>
  </div>

  <div id="talkingdead">
    <%= image_tag "shawn_zombie.jpg" %>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Roomr</title>
  <%= stylesheet_link_tag    'application', media: 'all' %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<div id="header">
  <h1>roomr</h1>
    <% if signed_in? %>
      <%= link_to current_user.email, current_user %>
</div>
      <%= link_to "Sign Out | ", session_path, method: :delete %>
      <%= link_to "Answer Some Questions | ", questionnaire_path %>
      <%= link_to "Join a City | ", regions_path %>
      <%= link_to "Your Conversations | ", conversations_path %>
      <%= link_to "Edit Your Profile", edit_user_path(current_user) %>
        <% else %>
      <%= link_to "Sign In", new_session_path %>
      <%= link_to "Sign Up", new_user_path %>
    <% end %>
  </div>

    <%= yield %>

  <% if flash[:error] %>
    <%= flash[:error] %>
  <% end %>
</body>
</html>

app/views/messages/_form.html.erb
<%= form_for [@other_user, @message] do |form| %>
  <div>
    <%= form.hidden_field :receiver_id, value: @other_user.id %>
  </div>

  <div>
    <%= form.label :body %>
    <%= form.text_area :body %>
  </div>

  <div>
    <%= form.submit "Send Message" %>
  </div>
<% end %>

app/views/messages/show.html.erb
<h2>Messages</h2>
<% @messages.each do |message| %>
  <%= message.sender.email %> - <%= message.body %>
<% end %>

app/views/questionnaires/show.html.erb
<div id="container">
  <div id="background">
    <div id="questionnaire">
      <% if @question %>
        <h2>Answer some questions:</h2>
      </br>
      <div>
        <h3><%= @question.prompt %></h3>
        <%= form_for @question.responses.new do |form| %>
          <%= form.hidden_field :question_id %>
        <div>
          <%= form.radio_button :positive, "0" %>
          <h5><%= form.label :true, @question.positive %></h5>
        </div>
        <div>
          <%= form.radio_button :positive, "1" %>
          <h5><%= form.label :false, @question.negative %></h5>
        </div>
        <%= form.submit "Answer!"%>
      <% end %>
      </div>
    <% else %>
      <h2>Questionnaire Complete!</h2>
    <% end %>
    </div>
  </div>
</div>

app/views/regions/_form.html.erb
<%= render "error_messages", target: region %>
<%= form_for region do |form| %>
  <%= form.label :name %>
  <%= form.text_field :name %>
  <%= form.submit "Add City" %>
<% end %>

app/views/regions/_join_button.html.erb
<% if current_user.region != region %>
  <%= form_for current_user do |form| %>
    <input type="hidden" name="back" value="true" />
    <%= form.hidden_field :region_id, value: @region.id %>
    <%= form.submit "Join City!" %>
  <% end %>
<% end %>

app/views/regions/_region.html.erb
<li><%= link_to region.name, region %></li>

app/views/regions/index.html.erb
<div id="container">
  <div id="regionmain">
    <ul>
      <h3><%= render @regions %></h3>
    </ul>
    </br>
      <% if current_user.admin? %>
        <%= render "form", region: @region %>
      <% end %>
    </br>
    <%= image_tag "zombie_city_1.jpg", alt: "Zombie city" %>
  </div>
</div>

app/views/regions/show.html.erb
<div id="container">
  <div id="regionshow">
    <h2>Welcome to <%= @region.name %>!</h2>
    <% if current_user.region == @region %>
      <p>(You're looking here)</p>
    <% end %>
    
    <br />
    <h3>Members</h3>
    <ul id="regionmemberlist">
      <% @users.each do |user| %>
        <% if user != current_user %>
          <li><%= link_to user.email, user %></li>
        <% end %>
      <% end %>
    </ul>
  <br />
    <%= render "regions/join_button", region: @region %>
    <%= image_tag "zombie_apocalypse.jpg" %>
  </div>
</div>

app/views/responses/_response.html.erb
<% if response.positive? %>
  <li>not <%= response.question.category %></li>
<% else %>
  <li><%= response.question.category %></li>
<% end %>

app/views/users/_form.html.erb
  <%= form_for user do |form| %>
    <div>
      <%= form.label :image %>
      <%= form.text_field :image %>
    </div>

    <div>
      <%= form.label :personal_statement %>
      <%= form.text_area :personal_statement %>
    </div>

    <%= form.submit %>
  <% end %>

app/views/users/edit.html.erb
<div id="container">
  <div id=profile>
    <h2>Edit Your Profile</h2>
    <%= render "form", user: @user %>
  </div>
</div>

app/views/users/new.html.erb
<%= form_for @user do |form| %>

  <% if @user.errors.any? %>
    <%= pluralize(@user.errors.count, "error") %> prevented your account from being created:
    <ul>
      <% @user.errors.full_messages.each do |error_message| %>
        <li><%= error_message %></li>
      <% end %>
    </ul>
  <% end %>

  <div>
    <%= form.label :email %>
    <%= form.email_field :email %>
  </div>
  <div>
    <%= form.label :password %>
    <%= form.password_field :password %>
  </div>
  <div>
    <%= form.submit "Sign up" %>
  </div>
<% end %>

app/views/users/show.html.erb
<div id="container">
  <div id="profile">
    <h2>Welcome to <%= @user.email %>'s Page</h2>
    <p><%= image_tag @user.image %></p>
    <h3>Personal Statement:</h3>
    <p><%= @user.personal_statement %></p>

    <% if @user != current_user %>
      <p>Send <%= link_to @user.email, user_conversation_path(@user) %>
  a message!</p>
  <% end %>

    <% if @user.responses.any? %>
      <h3><%= @user.email %> is:</h3>
    <ul>
      <%= render @responses %>
    </ul>
  <% end %>

  </div>
</div>